# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-HTML-2Text
version:      0.01
version_from: lib/Template/Plugin/HTML/2Text.pm
installdirs:  site
requires:
    HTML::FormatText::Html2text:   19
    Template:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
